name: Publish Builds

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  itch_project: quiyetbrul/flappy-bird
  BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
  BUILD_TYPE: Release

jobs:
  linux:
    name: Publish Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SFML
        run: sudo apt-get install libsfml-dev

      - name: Set up butler
        uses: jdno/setup-butler@v1

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Publish game to itch.io
        run: |
          butler push ${{github.workspace}}/build ${{ env.itch_project }}:linux-universal
