name: itch.io

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  quiyetbrul: quiyetbrul/flappy-bird

jobs:
  linux:
    name: Publish Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Install SFML
        run: sudo apt-get install libsfml-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

        # - name: Build
        #   # Build your program with the given configuration
        #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

        - name: Publish game to itch.io
          run: |
            butler push ${{github.workspace}} ${{ env.itch_project }}:linux-universal

      - name: Set up butler
        uses: jdno/setup-butler@v1

        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}

  macos:
    name: Publish MacOS Build
    runs-on: macos-latest

    steps:
      - name: Install SFML
        run: brew install sfml

      # - name: Configure CMake
      #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      # - name: Build
      #   # Build your program with the given configuration
      # run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Set up butler
        uses: jdno/setup-butler@v1

      - name: Publish game to itch.io
        run: |
          butler push ${{github.workspace}} ${{ env.itch_project }}:osx-universal
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
