name: itch.io

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  quiyetbrul: quiyetbrul/flappy-bird

jobs:
  linux:
    name: Publish Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Install SFML
        run: sudo apt-get install libsfml-dev

      - name: Build Game
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Publish game to itch.io
        run: |
          butler push ${{github.workspace}}/${{ env.itch_project }}:linux-universal
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}

  macos:
    name: Publish MacOS Build
    runs-on: macos-latest

    steps:
      - name: Install SFML
        run: brew install sfml

      - name: Build Game
        run: sh makerun.sh

      - name: Publish game to itch.io
        run: |
          butler push ${{github.workspace}}/${{ env.itch_project }}:osx-universal
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
