name: makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SFML
        run: brew intall sfml # sudo apt install -y libsfml-dev
      - name: build
        run: make all
