name: makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SFML
        run: brew install sfml
      - name: Build
        run: make all
