name: makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: install sfml
        run: brew install sfml
      - name: build
        run: make all

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install sfml
        run: sudo apt-get install libsfml-dev
      - name: build
        run: make all

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: install sfml - windows
        run: winget install sfml
      - name: build
        run: make all
