name: makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-project:
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
      include:
        - os: ubuntu-latest
          release_suffix: ubuntu
        - os: macos-latest
          release_suffix: mac
        - os: windows-latest
          release_suffix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install SFML - Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y libsfml-dev

      - name: Install SFML - MacOS
        if: matrix.os == 'macos-latest'
        run: brew install sfml

      - name: Install SFML - Windows
        if: matrix.os == 'windows-latest'
        run: choco install sfml

      - name: build
        run: make all
