name: makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SFML
        run: sudo apt install -y libsfml-dev
      - name: Run make
        run: make all
