name: makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SFML
        run: sudo apt install -y libsfml-dev
      - name: build
        run: make all
